version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
            - v1-npm-
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: Run tests with coverage
          command: npm run testcoverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  circleci:
    jobs:
      - test