const FETCH_PING_REQUEST = 'FETCH_PING_REQUEST';
const FETCH_PING_SUCCESS = 'FETCH_PING_SUCCESS';
const FETCH_PING_FAILURE = 'FETCH_PING_FAILURE';

export default {
  FETCH_PING_FAILURE,
  FETCH_PING_REQUEST,
  FETCH_PING_SUCCESS
};
